version: "3.3"

services:
  sonar:
    image: sonarqube:6.7.1-alpine
    ports:
      - "9001:9000"
      - "9092:9092"

  betvictor:
    image: jcarretero/betvictor:latest
    ports:
      - "8080:8080"